version: '3.9'

services:
  web:
    build: .
    container_name: web
    command: bash -c "python manage.py makemigrations app && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: project_db
    restart: always
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
